backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "data/home.json"
        fields:
          - { label: "Main Headline", name: "headline", widget: "string" }
          - { label: "Subheadline", name: "subheadline", widget: "text" }
