backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "business_data"
    label: "Local Businesses (live site data)"
    files:
      - label: "Businesses"
        name: "businesses"
        file: "data/businesses.js"
        editor:
          preview: false
        fields:
          - { label: "Businesses JS Content", name: "body", widget: "code", default_language: "javascript" }

