backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "business_data"
    label: "Local Businesses List"
    files:
      - label: "All Businesses"
        name: "businesses"
        file: "data/businesses.json"
        editor:
          preview: false
        fields:
          - { label: "Business Data Content", name: "body", widget: "code", default_language: "json" }
